### ISSUE TITLE
Register and release new version

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/ModelComparisons.jl#2]
Hi Rob,

Please register when everything is to your specification. Let me know if you need me to make any changes.

**Comment by goedman** [comment]
Hi Chris, think I've merged it all, just running a few more tests. One question, what do you think about a name such as `StatsModelComparisons.jl` to emphasize the statistical nature of the models. Sometimes I have used the term `regression models` but that might be too limited.

**Comment by itsdfish** [comment]
Yeah. I like that name. I think it emphasizes the statistical nature of the tests without making the name too narrow.

**Comment by itsdfish** [comment]
Rob, out of curiosity, what is your timeline for registering?

**Comment by storopoli** [comment]
What about `ModelComparisons.jl`?

**Comment by goedman** [comment]
It's in the pipeline but as it is a new package (name) the rule is 3 days before it is merged. I applied on Saturday p.m. so probably later today?

**Comment by itsdfish** [comment]
Sorry about that. I could not find an issue with the registration request.

**Comment by goedman** [comment]
No problem. I usually look at https://github.com/JuliaRegistries/General/pulls. Both packages I did on Saturday are listed as 3 days old.

**Comment by goedman** [comment]
Guess this is a consequence of using JuliaHub to register packages. I kind of assumed you would receive a Github notification.
